export const darkTheme = {
	name: 'dark',
	// General styling
	font: {
		family: 'Helvetica, \'Segoe UI\', sans-serif',
		weight: 300,
		titleColor: '#fff',
		subtitleColor: '#999',
		normalColor: '#fff',
		normalNegativeColor: '#fff',
		placeholderColor: '#aaa',
		linkColor: '#3573d9',
		linkActiveColor: '#df0000',
		linkVisitedColor: '#9156c4',
		code: {
			color: '#fff',
			background: '#000',
		},
		blockquote: '#2e70b1',
		keyboard: {
			color: '#fff',
			border: '#adb3b9',
			boxShadow: {
				outer: 'rgba(12, 13, 14, 0.2)',
				inner: '#fff',
			},
		},
		loading: {
			title: '#888',
			subtitle: '#ddd',
			normal: '#ccc',
			wave: 'rgba(255,255,255,0.5)',
		},
	},
	colors: {
		darkBackground: '#131313',
		mainBackground: '#333',
		mainHover: '#444',
		mainActive: '#555',
		hardBorder: '#ddd',
		softBorder: '#777',
		accents: {
			red: '#b40000',
			redFaded: 'rgba(180, 0, 0, 0.4)',
			green: '#080',
			greenFaded: 'rgba(0, 255, 0, 0.15)',
			blue: '#003cff',
			blueFaded: 'rgba(0, 60, 255, 0.5)',
		},
		error: '#f00',
		transparent: 'rgb(0,0,0,0)',
		// Special styling
		rainbow: {
			one: 'red',
			two: 'orange',
			three: 'yellow',
			four: 'green',
			five: 'cyan',
			six: 'blue',
			seven: 'indigo',
			eight: 'violet',
			nine: 'red',
		},
	},
};
