apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: website-acme
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: matt+letsencrypt@harmelodic.com
    privateKeySecretRef:
      name: letsencrypt
    solvers:
      - selector:
          dnsZones:
            - "harmelodic.com"
        dns01:
          cloudDNS:
            project: personal-prod-host-698399
            hostedZoneName: harmelodic-com
